  job:
      package-manager: github_actions
      allowed-updates:
          - update-type: all
      experiments:
          record-ecosystem-versions: true
      source:
          provider: github
          repo: PolymeshAssociation/polymesh-portal
          directory: /
          # branch: develop
      groups:
        actions-deps:
          patterns:
            - "*"