

  job:
      # package-manager: npm_and_yarn
      package-manager: github_actions
      allowed-updates:
          - update-type: all
      experiments:
          record-ecosystem-versions: true
      source:
          provider: github
          repo: PolymeshAssociation/polymesh-portal
          directory: /
          branch: develop