  job:
      package-manager: npm_and_yarn
      allowed-updates:
          - update-type: all
      experiments:
          record-ecosystem-versions: true
      source:
          provider: github
          repo: PolymeshAssociation/polymesh-portal
          directory: /
          # branch: develop
      groups:
        dev-deps:
          dependency-type: "development"
        prod-deps:
          dependency-type: "production"